# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jay Chen
title: Undergraduate Student
email: jc01@berkeley.edu
new website: https://jc01111.github.io/jc.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: JC01111
#instagram_username:
linkedin_username: jaychen01
#youtube_username: jaychen1117


# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
    Hi, my name's Jay and I'm a CS senior student at UC Berkeley. Currenly, I'm looking for job as Software Development Engineer.
    <br> <br>
    Alongside coding, my interests are:
      - Golf
      - Tennis
      - Music

content:
  - title: "Education" # Title for the section
    layout: "list" # Type of content section (list/text)
    content:
      - layout: "left"
        sub_title: "University of California, Berkeley<br> B.A. Computer Science"
        caption: "Present - 2024<br><br>GPA: 3.49/4.00"
        description: |
          Core Courses: Efficient Algorithms and Intractable Problems, Optimization Models in Engineering, Introduction to Artificial Intelligence
          , Computer Security, Data Structures, Concepts of Probability


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        sub_title: Undergraduate Researcher
        link:
        # link_text: boringcompany.com
        sub_title: Kennesaw State University, Dr. Yixin Xie's Lab
        caption: Dec 2022 - Present
#        quote: >
        description: | # this will include new lines to allow paragraphs
          - Applying and Optimizing Machine Learning Algorithms (random forest, GNN, etc.) in biological data analysis
          - Developing tools (Shell script) to perform Molecular Dynamic simulations, increased calculation speed by 80%

      - layout: top-left
        sub_title: Pacman AI
        caption: Sep 2023
        description: |
            - Used Advanced Algorithms to find the optimized route to escape the maze and eat all the dots
        
      - layout: top-left
        sub_title: Currency Exchange
        caption: March 2023
        description: |
          - Web scrape the latest currency of USD to RMB online, then help with calculating the amount of money needed to exchange between USD and RMB

  - title: Publication
    layout: text
    content: | # this will include new lines to allow paragraphs
      [1] Computational Study on DNA Repair: The Roles of Electrostatic Interactions between Uracil-DNA Glycosylase(UDG) and DNA. Xie, Y., Karki, C. B., **Chen, J.**, Liu, D., Li, L. (2021). Frontiers in Molecular Biosciences, 8, 681. [[link]](https://www.frontiersin.org/articles/10.3389/fmolb.2021.718587/full)
      <br> <br>
      [2] Using a comprehensive approach to investigate the interaction between Kinesin-5/Eg5 and the microtubule. Guo, W., Sun, S., Sanchez, J. E., Lopez-Hernandez, A. E., Ale, T. A., **Chen, J.**, ... Li, L. (2022). Computational and structural biotechnology journal, 20, 4305-4314.
          [[link]](https://www.sciencedirect.com/science/article/pii/S2001037022003543)

  - title: Technical Skills
    layout: text
    content: |
      Programming Language: Java, Python, C++, Assembly Language, Shell Script, etc.
      <br>
      Framework and Tools: Intellij, JUnit, Git, Xcode, Atom, Matlab, SQL, Jupyter Notebook, Latex, etc.


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
